# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here- image: circleci/node:8
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: eslint tests
          command: |
            mkdir -p test-results/eslint
            yarn run eslint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/junit.xml

      # - persist_to_workspace:
      #     root: ~/test-results
      #     paths:
      #       - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
